import type { KarnetEvent } from "@/lib/types";

export const EVENTS: KarnetEvent[] = [
  {
    id: "e1",
    slug: "nokturny-jesienne",
    title_pl: "Nokturny Jesienne",
    title_en: "Autumn Nocturnes",
    description_pl:
      "Wieczór kameralnej muzyki klasycznej — Chopin i Debussy w wykonaniu młodych solistów Filharmonii Miejskiej.",
    description_en:
      "An evening of chamber classical music — Chopin and Debussy performed by young soloists of the Municipal Philharmonic.",
    start_date: "2026-09-12T19:00:00+02:00",
    end_date: "2026-09-12T21:00:00+02:00",
    place_slug: "filharmonia-miejska",
    category_slugs: ["muzyka"],
    article_slugs: [],
    ticket_url: "https://tickets.example.com/nokturny-jesienne",
    ticket_price_info_pl: "40–80 zł",
    ticket_price_info_en: "40–80 PLN",
    is_free: false,
    is_editorial_pick: true,
    pick_note_pl: "Kameralnie, blisko sceny i naprawdę wzruszająco — jeden z naszych ulubionych wieczorów tej jesieni.",
    pick_note_en: "Intimate, close to the stage, genuinely moving — one of our favourite evenings this autumn.",
    picked_by_author_slug: "piotr-zawadzki",
    meta_description_pl: "Wieczór kameralnej muzyki klasycznej w Filharmonii Miejskiej w Krakowie.",
    meta_description_en: "An evening of chamber classical music at the Municipal Philharmonic in Kraków.",
  },
  {
    id: "e2",
    slug: "smocze-granie",
    title_pl: "Smocze Granie",
    title_en: "Dragon's Tune Festival",
    description_pl:
      "Trzydniowy festiwal muzyki na świeżym powietrzu nad Wisłą — sceny lokalne, foodtrucki i warsztaty dla dzieci.",
    description_en:
      "A three-day open-air music festival on the Vistula boulevards — local stages, food trucks, and kids' workshops.",
    start_date: "2026-09-18T16:00:00+02:00",
    end_date: "2026-09-20T23:00:00+02:00",
    place_slug: "ogrod-kultury",
    category_slugs: ["festiwale", "muzyka"],
    article_slugs: ["karnet-oglasza-smocze-granie"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    is_editorial_pick: false,
    meta_description_pl: "Trzydniowy festiwal muzyczny nad Wisłą w Krakowie — wstęp wolny.",
    meta_description_en: "A three-day music festival on the Vistula in Kraków — free entry.",
  },
  {
    id: "e3",
    slug: "sen-nocy-letniej",
    title_pl: "Sen nocy letniej",
    title_en: "A Midsummer Night's Dream",
    description_pl: "Nowa, muzyczna inscenizacja komedii Szekspira w Teatrze Pod Żaglem.",
    description_en: "A new, musical staging of Shakespeare's comedy at Teatr Pod Żaglem.",
    start_date: "2026-09-14T19:30:00+02:00",
    end_date: "2026-09-14T22:00:00+02:00",
    place_slug: "teatr-pod-zaglem",
    category_slugs: ["teatr"],
    article_slugs: ["sen-nocy-letniej-recenzja"],
    ticket_url: "https://tickets.example.com/sen-nocy-letniej",
    ticket_price_info_pl: "35–60 zł",
    ticket_price_info_en: "35–60 PLN",
    is_free: false,
    accessibility_override: { captions_available: true },
    is_editorial_pick: false,
    meta_description_pl: "Muzyczna inscenizacja komedii Szekspira w Teatrze Pod Żaglem.",
    meta_description_en: "A musical staging of Shakespeare's comedy at Teatr Pod Żaglem.",
  },
  {
    id: "e4",
    slug: "retrospektywa-kina-srodkowej-europy",
    title_pl: "Retrospektywa: Kino Środkowej Europy",
    title_en: "Retrospective: Central European Cinema",
    description_pl: "Tydzień pokazów klasyki kina czeskiego, węgierskiego i polskiego w cyfrowo zremasterowanych kopiach.",
    description_en: "A week of screenings of classic Czech, Hungarian, and Polish cinema in remastered digital copies.",
    start_date: "2026-09-15T00:00:00+02:00",
    end_date: "2026-09-21T23:59:00+02:00",
    place_slug: "kino-panorama-krakow",
    category_slugs: ["film"],
    article_slugs: ["czego-oczekiwac-retrospektywa"],
    ticket_url: "https://tickets.example.com/retrospektywa",
    ticket_price_info_pl: "25 zł / seans",
    ticket_price_info_en: "25 PLN / screening",
    is_free: false,
    is_editorial_pick: false,
    meta_description_pl: "Tydzień klasyki kina Europy Środkowej w Kinie Panorama Kraków.",
    meta_description_en: "A week of Central European film classics at Kino Panorama Kraków.",
  },
  {
    id: "e5",
    slug: "wieczor-poezji-wspolczesnej",
    title_pl: "Wieczór poezji współczesnej",
    title_en: "An Evening of Contemporary Poetry",
    description_pl: "Czytanie na głos i rozmowa z trójką młodych poetów krakowskiej sceny literackiej.",
    description_en: "A reading and conversation with three young poets from Kraków's literary scene.",
    start_date: "2026-09-16T18:30:00+02:00",
    end_date: "2026-09-16T20:00:00+02:00",
    place_slug: "biblioteka-na-kazimierzu",
    category_slugs: ["literatura"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    accessibility_override: { quiet_zone_available: true },
    is_editorial_pick: false,
    meta_description_pl: "Wieczór poezji współczesnej w Bibliotece na Kazimierzu.",
    meta_description_en: "An evening of contemporary poetry at the Kazimierz Library.",
  },
  {
    id: "e6",
    slug: "swiatla-miasta",
    title_pl: "Światła miasta",
    title_en: "City Lights",
    description_pl: "Wystawa fotografii nocnego Krakowa — sześć tygodni, jedna galeria, setki kadrów.",
    description_en: "An exhibition of night photography of Kraków — six weeks, one gallery, hundreds of frames.",
    start_date: "2026-09-10T10:00:00+02:00",
    end_date: "2026-10-30T18:00:00+02:00",
    place_slug: "galeria-nowa-fala",
    category_slugs: ["wystawy"],
    article_slugs: ["rozmowa-z-kuratorka-swiatla-miasta"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    is_editorial_pick: true,
    pick_note_pl: "Wpadnijcie o zmierzchu — światło w galerii najlepiej gra z fotografiami tuż przed zamknięciem.",
    pick_note_en: "Come at dusk — the gallery light plays best with the photographs just before closing.",
    picked_by_author_slug: "aleksandra-kmiecik",
    meta_description_pl: "Wystawa nocnej fotografii Krakowa w Galerii Nowa Fala.",
    meta_description_en: "An exhibition of Kraków night photography at Nowa Fala Gallery.",
  },
  {
    id: "e7",
    slug: "jarmark-sztuki-ludowej",
    title_pl: "Jarmark Sztuki Ludowej",
    title_en: "Folk Art Fair",
    description_pl: "Rękodzieło, ceramika i muzyka ludowa — coroczny jarmark tuż za granicami miasta.",
    description_en: "Handicrafts, ceramics, and folk music — an annual fair just outside the city.",
    start_date: "2026-09-27T10:00:00+02:00",
    end_date: "2026-09-27T18:00:00+02:00",
    place_slug: "ogrod-kultury",
    category_slugs: ["okolice-krakowa"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    is_editorial_pick: false,
    meta_description_pl: "Doroczny jarmark sztuki ludowej w okolicach Krakowa.",
    meta_description_en: "The annual folk art fair near Kraków.",
  },
  {
    id: "e8",
    slug: "noc-klubowa-elektronika-spod-wawelu",
    title_pl: "Noc klubowa: Elektronika spod Wawelu",
    title_en: "Club Night: Electronic Sounds of Kraków",
    description_pl: "Lokalni producenci elektroniki na jednej scenie — do białego rana.",
    description_en: "Local electronic producers on one stage — until sunrise.",
    start_date: "2026-09-19T22:00:00+02:00",
    end_date: "2026-09-20T05:00:00+02:00",
    place_slug: "klub-podziemie",
    category_slugs: ["muzyka"],
    ticket_url: "https://tickets.example.com/noc-klubowa",
    ticket_price_info_pl: "30–50 zł",
    ticket_price_info_en: "30–50 PLN",
    is_free: false,
    is_editorial_pick: false,
    meta_description_pl: "Noc muzyki elektronicznej w Klubie Podziemie w Krakowie.",
    meta_description_en: "A night of electronic music at Klub Podziemie in Kraków.",
  },
  {
    id: "e9",
    slug: "dni-otwarte-muzeum-czasu",
    title_pl: "Dni otwarte Muzeum Czasu",
    title_en: "Museum of Time Open Days",
    description_pl: "Bezpłatny wstęp i oprowadzania kuratorskie przez cały weekend.",
    description_en: "Free entry and curator-led tours all weekend.",
    start_date: "2026-09-21T10:00:00+02:00",
    end_date: "2026-09-21T17:00:00+02:00",
    place_slug: "muzeum-czasu",
    category_slugs: ["wystawy"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    is_editorial_pick: false,
    meta_description_pl: "Bezpłatny weekend otwartych drzwi w Muzeum Czasu.",
    meta_description_en: "A free open-doors weekend at the Museum of Time.",
  },
  {
    id: "e10",
    slug: "kabaret-na-bis",
    title_pl: "Kabaret na bis",
    title_en: "Cabaret Encore",
    description_pl: "Wieczór improwizowanego kabaretu z udziałem krakowskich grup studenckich.",
    description_en: "An evening of improvised cabaret featuring Kraków student troupes.",
    start_date: "2026-09-25T19:00:00+02:00",
    end_date: "2026-09-25T21:30:00+02:00",
    place_slug: "centrum-kultury-podgorze",
    category_slugs: ["teatr"],
    ticket_url: "https://tickets.example.com/kabaret-na-bis",
    ticket_price_info_pl: "20–35 zł",
    ticket_price_info_en: "20–35 PLN",
    is_free: false,
    is_editorial_pick: false,
    meta_description_pl: "Wieczór kabaretu improwizowanego w Centrum Kultury Podgórze.",
    meta_description_en: "An evening of improvised cabaret at the Podgórze Cultural Centre.",
  },
  {
    id: "e11",
    slug: "festiwal-filmow-krotkometrazowych",
    title_pl: "Festiwal Filmów Krótkometrażowych",
    title_en: "Short Film Festival",
    description_pl: "Cztery dni krótkiego kina z całego świata i spotkania z twórcami po pokazach.",
    description_en: "Four days of short films from around the world, with Q&As after screenings.",
    start_date: "2026-10-02T12:00:00+02:00",
    end_date: "2026-10-05T22:00:00+02:00",
    place_slug: "kino-panorama-krakow",
    category_slugs: ["film", "festiwale"],
    ticket_url: "https://tickets.example.com/festiwal-krotkometrazowy",
    ticket_price_info_pl: "15–25 zł",
    ticket_price_info_en: "15–25 PLN",
    is_free: false,
    is_editorial_pick: true,
    pick_note_pl: "Cztery lata z rzędu wybieramy stąd nasz ulubiony film sezonu — polecamy blok sobotni.",
    pick_note_en: "Four years running we've found our favourite short of the season here — the Saturday block is the one to catch.",
    picked_by_author_slug: "aleksandra-kmiecik",
    meta_description_pl: "Czterodniowy festiwal filmów krótkometrażowych w Kinie Panorama Kraków.",
    meta_description_en: "A four-day short film festival at Kino Panorama Kraków.",
  },
  {
    id: "e12",
    slug: "spotkanie-z-autorem-wywiad-na-zywo",
    title_pl: "Spotkanie z autorem: wywiad na żywo",
    title_en: "Author Talk: Live Interview",
    description_pl: "Rozmowa z krakowskim reportażystą o jego najnowszej książce.",
    description_en: "A conversation with a Kraków-based reportage writer about their latest book.",
    start_date: "2026-09-23T18:00:00+02:00",
    end_date: "2026-09-23T19:30:00+02:00",
    place_slug: "biblioteka-na-kazimierzu",
    category_slugs: ["literatura"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    is_editorial_pick: false,
    meta_description_pl: "Spotkanie autorskie w Bibliotece na Kazimierzu.",
    meta_description_en: "An author talk at the Kazimierz Library.",
  },
  {
    id: "e13",
    slug: "symfonia-dla-krakowa",
    title_pl: "Symfonia dla Krakowa",
    title_en: "A Symphony for Kraków",
    description_pl: "Prawykonanie nowej symfonii inspirowanej historią miasta, z udziałem chóru i orkiestry.",
    description_en: "The premiere of a new symphony inspired by the city's history, with choir and orchestra.",
    start_date: "2026-10-10T19:00:00+02:00",
    end_date: "2026-10-10T21:15:00+02:00",
    place_slug: "filharmonia-miejska",
    category_slugs: ["muzyka"],
    ticket_url: "https://tickets.example.com/symfonia-dla-krakowa",
    ticket_price_info_pl: "50–120 zł",
    ticket_price_info_en: "50–120 PLN",
    is_free: false,
    accessibility_override: { audio_description_available: true },
    is_editorial_pick: false,
    meta_description_pl: "Prawykonanie nowej symfonii w Filharmonii Miejskiej w Krakowie.",
    meta_description_en: "The premiere of a new symphony at the Municipal Philharmonic in Kraków.",
  },
  {
    id: "e14",
    slug: "sztuka-ulicy-performance-w-plenerze",
    title_pl: "Sztuka ulicy: performance w plenerze",
    title_en: "Street Art: Outdoor Performance",
    description_pl: "Interdyscyplinarny performance łączący taniec, projekcje i muzykę na żywo.",
    description_en: "An interdisciplinary performance combining dance, projection, and live music.",
    start_date: "2026-09-13T20:00:00+02:00",
    end_date: "2026-09-13T21:00:00+02:00",
    place_slug: "ogrod-kultury",
    category_slugs: ["wystawy", "okolice-krakowa"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    is_editorial_pick: false,
    meta_description_pl: "Plenerowy performance łączący taniec, projekcje i muzykę.",
    meta_description_en: "An outdoor performance combining dance, projection, and live music.",
  },
  {
    id: "e15",
    slug: "teatr-cieni-basnie-slowianskie",
    title_pl: "Teatr cieni: baśnie słowiańskie",
    title_en: "Shadow Theatre: Slavic Fairy Tales",
    description_pl: "Spektakl dla całej rodziny w formie teatru cieni, oparty na dawnych baśniach słowiańskich.",
    description_en: "A family shadow-theatre show based on old Slavic fairy tales.",
    start_date: "2026-09-20T11:00:00+02:00",
    end_date: "2026-09-20T12:00:00+02:00",
    place_slug: "teatr-pod-zaglem",
    category_slugs: ["teatr"],
    ticket_url: "https://tickets.example.com/teatr-cieni",
    ticket_price_info_pl: "20 zł",
    ticket_price_info_en: "20 PLN",
    is_free: false,
    accessibility_override: { quiet_zone_available: true },
    is_editorial_pick: true,
    pick_note_pl: "Ściszone światła, spokojne tempo — dobry wybór na pierwszy teatralny wieczór z dzieckiem.",
    pick_note_en: "Dimmed lights, gentle pacing — a good pick for a child's first evening at the theatre.",
    picked_by_author_slug: "magdalena-wrobel",
    meta_description_pl: "Spektakl teatru cieni dla całej rodziny w Teatrze Pod Żaglem.",
    meta_description_en: "A family shadow-theatre show at Teatr Pod Żaglem.",
  },
  {
    id: "e16",
    slug: "podgorze-dzielnica-w-obiektywie",
    title_pl: "Wystawa: Podgórze — dzielnica w obiektywie",
    title_en: "Exhibition: Podgórze Through the Lens",
    description_pl: "Zbiorowa wystawa fotografii lokalnych twórców dokumentujących zmieniające się Podgórze.",
    description_en: "A group photography exhibition documenting the changing face of Podgórze.",
    start_date: "2026-09-05T10:00:00+02:00",
    end_date: "2026-11-15T18:00:00+02:00",
    place_slug: "centrum-kultury-podgorze",
    category_slugs: ["wystawy"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    is_editorial_pick: false,
    meta_description_pl: "Wystawa fotografii dokumentującej dzielnicę Podgórze.",
    meta_description_en: "A photography exhibition documenting the Podgórze district.",
  },
  {
    id: "e17",
    slug: "rytmy-swiata",
    title_pl: "Rytmy świata: koncert muzyki etnicznej",
    title_en: "Rhythms of the World: World Music Concert",
    description_pl: "Muzycy z czterech kontynentów na jednej scenie w dawnej zajezdni tramwajowej.",
    description_en: "Musicians from four continents share one stage in a former tram depot.",
    start_date: "2026-10-18T19:00:00+02:00",
    end_date: "2026-10-18T21:30:00+02:00",
    place_slug: "stara-zajezdnia-sztuki",
    category_slugs: ["muzyka"],
    ticket_url: "https://tickets.example.com/rytmy-swiata",
    ticket_price_info_pl: "40 zł",
    ticket_price_info_en: "40 PLN",
    is_free: false,
    is_editorial_pick: false,
    meta_description_pl: "Koncert muzyki etnicznej w Starej Zajezdni Sztuki.",
    meta_description_en: "A world music concert at Stara Zajezdnia Arts Depot.",
  },
  {
    id: "e18",
    slug: "zajezdnia-prezentuje-sztuka-nowych-mediow",
    title_pl: "Zajezdnia prezentuje: sztuka nowych mediów",
    title_en: "Zajezdnia Presents: New Media Art",
    description_pl: "Wystawa instalacji wideo i sztuki generatywnej młodych twórców z regionu.",
    description_en: "An exhibition of video installations and generative art by regional emerging artists.",
    start_date: "2026-09-28T10:00:00+02:00",
    end_date: "2026-10-12T19:00:00+02:00",
    place_slug: "stara-zajezdnia-sztuki",
    category_slugs: ["wystawy", "inne"],
    ticket_price_info_pl: "Wstęp wolny",
    ticket_price_info_en: "Free entry",
    is_free: true,
    is_editorial_pick: true,
    pick_note_pl: "Najciekawszy pokaz sztuki nowych mediów w mieście w tym sezonie — zarezerwujcie sobie godzinę.",
    pick_note_en: "The most interesting new media show in the city this season — set aside a full hour.",
    picked_by_author_slug: "aleksandra-kmiecik",
    meta_description_pl: "Wystawa sztuki nowych mediów w Starej Zajezdni Sztuki.",
    meta_description_en: "A new media art exhibition at Stara Zajezdnia Arts Depot.",
  },
];

export function findEvent(slug: string): KarnetEvent | undefined {
  return EVENTS.find((e) => e.slug === slug);
}
