import type { Place } from "@/lib/types";

// Venue names below are fictional (this is demo/seed content for a UI build),
// scattered across real Kraków-style locations for realistic map behaviour.
export const PLACES: Place[] = [
  {
    id: "p1",
    slug: "teatr-pod-zaglem",
    name_pl: "Teatr Pod Żaglem",
    name_en: "Teatr Pod Żaglem",
    address: "ul. Karmelicka 12, Kraków",
    latitude: 50.0625,
    longitude: 19.9356,
    description_pl:
      "Kameralna scena dramatyczna w sercu miasta, znana z odważnego repertuaru i spektakli dla całej rodziny.",
    description_en:
      "An intimate drama stage in the heart of the city, known for bold programming and family-friendly shows.",
    category_slugs: ["teatry"],
    neighbourhood_slug: "stare-miasto",
    accessibility_profile: {
      wheelchair_accessible: "yes",
      induction_loop: true,
      captions_available: false,
      audio_description_available: false,
      quiet_zone_available: false,
      accessible_toilet: true,
      accessible_parking: false,
      notes_pl: "Wejście dla wózków od podwórza, prosimy o wcześniejszy kontakt z obsługą widowni.",
      notes_en: "Wheelchair entrance via the courtyard — please contact front-of-house in advance.",
    },
  },
  {
    id: "p2",
    slug: "muzeum-czasu",
    name_pl: "Muzeum Czasu",
    name_en: "Museum of Time",
    address: "Rynek Główny 5, Kraków",
    latitude: 50.0616,
    longitude: 19.9377,
    description_pl:
      "Muzeum poświęcone historii mierzenia czasu, od słonecznych zegarów po krakowski hejnał.",
    description_en:
      "A museum devoted to the history of timekeeping, from sundials to the Kraków bugle call.",
    category_slugs: ["muzea"],
    neighbourhood_slug: "stare-miasto",
    accessibility_profile: {
      wheelchair_accessible: "partial",
      induction_loop: false,
      captions_available: false,
      audio_description_available: true,
      quiet_zone_available: false,
      accessible_toilet: true,
      accessible_parking: false,
      notes_pl: "Parter w pełni dostępny, piętro tylko schodami.",
      notes_en: "Ground floor fully accessible; upper floor by stairs only.",
    },
  },
  {
    id: "p3",
    slug: "galeria-nowa-fala",
    name_pl: "Galeria Nowa Fala",
    name_en: "Nowa Fala Gallery",
    address: "Plac Szczepański 3, Kraków",
    latitude: 50.0632,
    longitude: 19.9361,
    description_pl: "Galeria sztuki współczesnej prezentująca młodych artystów z Polski i Europy Środkowej.",
    description_en: "A contemporary art gallery showcasing emerging artists from Poland and Central Europe.",
    category_slugs: ["galerie"],
    neighbourhood_slug: "stare-miasto",
    accessibility_profile: {
      wheelchair_accessible: "yes",
      induction_loop: false,
      captions_available: false,
      audio_description_available: false,
      quiet_zone_available: true,
      accessible_toilet: true,
      accessible_parking: false,
    },
  },
  {
    id: "p4",
    slug: "kino-panorama-krakow",
    name_pl: "Kino Panorama Kraków",
    name_en: "Kino Panorama Kraków",
    address: "ul. Karmelicka 45, Kraków",
    latitude: 50.0658,
    longitude: 19.933,
    description_pl: "Kameralne kino studyjne z jedną z niewielu w mieście sal z pętlą indukcyjną.",
    description_en: "An independent arthouse cinema, one of the few in the city with a hearing-loop screen.",
    category_slugs: ["kina"],
    neighbourhood_slug: "stare-miasto",
    accessibility_profile: {
      wheelchair_accessible: "yes",
      induction_loop: true,
      captions_available: true,
      audio_description_available: true,
      quiet_zone_available: false,
      accessible_toilet: true,
      accessible_parking: true,
    },
  },
  {
    id: "p5",
    slug: "klub-podziemie",
    name_pl: "Klub Podziemie",
    name_en: "Klub Podziemie",
    address: "ul. Krakowska 22, Kraków",
    latitude: 50.058,
    longitude: 19.94,
    description_pl: "Klubowa piwnica z najlepszym brzmieniem sceny elektronicznej i alternatywnej w mieście.",
    description_en: "A basement club with the best sound on the city's electronic and alternative scene.",
    category_slugs: ["kluby-muzyczne"],
    neighbourhood_slug: "kazimierz",
    accessibility_profile: {
      wheelchair_accessible: "no",
      induction_loop: false,
      captions_available: false,
      audio_description_available: false,
      quiet_zone_available: false,
      accessible_toilet: false,
      accessible_parking: false,
      notes_pl: "Lokal w piwnicy, dostępny wyłącznie po schodach — brak windy ani podjazdu.",
      notes_en: "Basement venue reachable only by stairs — no lift or ramp available.",
    },
  },
  {
    id: "p6",
    slug: "ogrod-kultury",
    name_pl: "Ogród Kultury",
    name_en: "Ogród Kultury",
    address: "Bulwary Wiślane, Kraków",
    latitude: 50.054,
    longitude: 19.941,
    description_pl: "Plenerowa scena nad Wisłą, gospodarz letnich festiwali i koncertów pod gołym niebem.",
    description_en: "An open-air stage on the Vistula boulevards, host to summer festivals and outdoor concerts.",
    category_slugs: ["plener"],
    neighbourhood_slug: "kazimierz",
    accessibility_profile: {
      wheelchair_accessible: "yes",
      induction_loop: false,
      captions_available: false,
      audio_description_available: false,
      quiet_zone_available: false,
      accessible_toilet: true,
      accessible_parking: true,
    },
  },
  {
    id: "p7",
    slug: "biblioteka-na-kazimierzu",
    name_pl: "Biblioteka na Kazimierzu",
    name_en: "Kazimierz Library",
    address: "ul. Miodowa 9, Kraków",
    latitude: 50.0512,
    longitude: 19.9445,
    description_pl: "Dzielnicowa biblioteka ze strefą ciszy i regularnym programem spotkań autorskich.",
    description_en: "A neighbourhood library with a quiet zone and a regular programme of author events.",
    category_slugs: ["biblioteki"],
    neighbourhood_slug: "kazimierz",
    accessibility_profile: {
      wheelchair_accessible: "yes",
      induction_loop: false,
      captions_available: false,
      audio_description_available: false,
      quiet_zone_available: true,
      accessible_toilet: true,
      accessible_parking: false,
    },
  },
  {
    id: "p8",
    slug: "centrum-kultury-podgorze",
    name_pl: "Centrum Kultury Podgórze",
    name_en: "Podgórze Cultural Centre",
    address: "Rynek Podgórski 1, Kraków",
    latitude: 50.045,
    longitude: 19.948,
    description_pl: "Dom kultury dzielnicy Podgórze — warsztaty, kabaret, wystawy lokalnych twórców.",
    description_en: "The Podgórze district's cultural centre — workshops, cabaret, and exhibitions by local artists.",
    category_slugs: ["domy-i-centra-kultury"],
    neighbourhood_slug: "podgorze",
    accessibility_profile: {
      wheelchair_accessible: "yes",
      induction_loop: false,
      captions_available: false,
      audio_description_available: false,
      quiet_zone_available: false,
      accessible_toilet: true,
      accessible_parking: true,
    },
  },
  {
    id: "p9",
    slug: "stara-zajezdnia-sztuki",
    name_pl: "Stara Zajezdnia Sztuki",
    name_en: "Stara Zajezdnia Arts Depot",
    address: "ul. Wawrzyńca 12, Kraków",
    latitude: 50.0505,
    longitude: 19.9515,
    description_pl: "Dawna zajezdnia tramwajowa zamieniona na przestrzeń wystawienniczo-koncertową.",
    description_en: "A former tram depot converted into an exhibition and concert space.",
    category_slugs: ["galerie", "inne"],
    neighbourhood_slug: "podgorze",
    accessibility_profile: {
      wheelchair_accessible: "partial",
      induction_loop: false,
      captions_available: false,
      audio_description_available: false,
      quiet_zone_available: false,
      accessible_toilet: true,
      accessible_parking: false,
      notes_pl: "Hala główna dostępna dla wózków, antresola tylko schodami.",
      notes_en: "Main hall is wheelchair accessible; the mezzanine is stairs-only.",
    },
  },
  {
    id: "p10",
    slug: "filharmonia-miejska",
    name_pl: "Filharmonia Miejska",
    name_en: "Municipal Philharmonic",
    address: "ul. Zwierzyniecka 1, Kraków",
    latitude: 50.06,
    longitude: 19.93,
    description_pl: "Sala koncertowa muzyki klasycznej z pełnym zapleczem dostępności.",
    description_en: "A classical concert hall with full accessibility provisions.",
    category_slugs: ["kluby-muzyczne"],
    neighbourhood_slug: "zwierzyniec",
    accessibility_profile: {
      wheelchair_accessible: "yes",
      induction_loop: true,
      captions_available: false,
      audio_description_available: true,
      quiet_zone_available: true,
      accessible_toilet: true,
      accessible_parking: true,
    },
  },
];

export function findPlace(slug: string): Place | undefined {
  return PLACES.find((p) => p.slug === slug);
}
